remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: spike-rush
layout: default
description: Spike Rush: Pygame Implemenation is a top down shooter where two players compete by attacking and defending a single spike site. 